theme: jekyll-theme-cayman
title: Hermen@uta
description: "Navigating meaning in the digital age."
show_downloads: false
author: "Antonio Carlos Olivieri"
baseurl: "/Hermenauta"
logo: "/img/logo.png"
